site_name: HTML Elements
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
- HTML Elements: index.md
- Getting started: getting_started.md
- Background: background.md
- Basic reference: basic_reference.md
- Extended reference: extended_reference.md
- Extensions: extensions.md