statuses = [
    {"label": "Draft", "value": "draft"},
    {"label": "New", "value": "new"},
    {"label": "Needs revision", "value": "needsRevision"},
    {"label": "In Approval", "value": "inApproval"},
    {"label": "In Review", "value": "inReview"},
    {"label": "Ready for Export", "value": "readyForExport"},
    {"label": "Exported", "value": "exported"},
    {"label": "Rejected", "value": "rejected"},
]
entities = [
    {"id": "1", "name": "Legal Entity 1"},
    {"id": "2", "name": "Legal Entity 2"},
    {"id": "3", "name": "Legal Entity 3"},
    {"id": "4", "name": "Legal Entity 4"},
]

currencies = [
    {"label": "EUR", "value": "EUR"},
    {"label": "CHF", "value": "CHF"},
    {"label": "USD", "value": "USD"},
    {"label": "SEK", "value": "SEK"},
]

suppliers = [
    {
        "id": "1234",
        "name": "Supplier 1",
    },
    {
        "id": "1232",
        "name": "Supplier 2",
    },
    {
        "id": "1235",
        "name": "Supplier 4",
    },
    {
        "id": "1239",
        "name": "Supplier 3",
    },
    {
        "id": "000",
        "name": "Supplier 0",
    },
    {
        "id": "fjewifw",
        "name": "Supplier 11",
    },
]

purchase_orders = [
    {
        "id": "1",
        "name": "Purchase order 1",
        "supplierId": "1234",
    },
    {
        "id": "2",
        "name": "Purchase order 2",
        "supplierId": "1234",
    },
    {
        "id": "3",
        "name": "Purchase order 3",
        "supplierId": "1234",
    },
    {
        "id": "4",
        "name": "Purchase order 4",
        "supplierId": "1234",
    },
    {
        "id": "5",
        "name": "Purchase order 5",
        "supplierId": "1232",
    },
    {
        "id": "6",
        "name": "Purchase order 6",
        "supplierId": "1232",
    },
    {
        "id": "7",
        "name": "Purchase order 7",
        "supplierId": "1232",
    },
    {
        "id": "8",
        "name": "Purchase order 8",
        "supplierId": "1239",
    },
    {
        "id": "9",
        "name": "Purchase order 9",
        "supplierId": "1234",
    },
]

users = [
    {"id": "1", "name": "Anton De Meester"},
    {"id": "2", "name": "Arnold Schumacher"},
    {"id": "3", "name": "Benedikt Cucumber"},
    {"id": "4", "name": "Rober Not of Hear-o"},
    {"id": "5", "name": "That guy from Hamilton"},
    {"id": "6", "name": "Tomis Cruising"},
    {"id": "7", "name": "Ikea Matata"},
    {"id": "8", "name": "Yokoy Bot"},
]

line_items = [
    {
        "id": "1",
        "categoryId": "1",
        "costObjectId": "1",
        "description": "This is a line item",
        "gross": 500,
        "net": 500,
        "taxRateId": "1",
        "quantity": 20,
    },
    {
        "id": "2",
        "categoryId": None,
        "costObjectId": None,
        "description": None,
        "gross": 0,
        "net": 0,
        "taxRateId": None,
        "quantity": None,
    },
    {
        "id": "3",
        "categoryId": "1",
        "costObjectId": "1",
        "description": "This is a line item",
        "gross": 500,
        "net": 500,
        "taxRateId": "1",
        "quantity": 20,
    },
    {
        "id": "4",
        "categoryId": "1",
        "costObjectId": "1",
        "description": "This is a line item",
        "gross": 500,
        "net": 500,
        "taxRateId": "1",
        "quantity": 20,
    },
    {
        "id": "5",
        "categoryId": "1",
        "costObjectId": "1",
        "description": "This is a line item",
        "gross": 500,
        "net": 500,
        "taxRateId": "1",
        "quantity": 20,
    },
    {
        "id": "6",
        "categoryId": "1",
        "costObjectId": "1",
        "description": "This is a line item",
        "gross": 500,
        "net": 500,
        "taxRateId": "1",
        "quantity": 20,
    },
    {
        "id": "7",
        "categoryId": "1",
        "costObjectId": "1",
        "description": "This is a line item",
        "gross": 500,
        "net": 500,
        "taxRateId": "1",
        "quantity": 20,
    },
]

categories = [
    {"id": "1", "name": "Category 1"},
    {"id": "2", "name": "Category 2"},
    {"id": "3", "name": "Category 3"},
    {"id": "4", "name": "Category 4"},
    {"id": "5", "name": "Category 5"},
]

cost_objects = [
    {"id": "1", "name": "Cost Object 1"},
    {"id": "2", "name": "Cost Object 2"},
    {"id": "3", "name": "Cost Object 3"},
    {"id": "4", "name": "Cost Object 4"},
    {"id": "5", "name": "Cost Object 5"},
]

tax_rates = [
    {"id": "1", "name": "Tax Rates 1"},
    {"id": "2", "name": "Tax Rates 2"},
    {"id": "3", "name": "Tax Rates 3"},
    {"id": "4", "name": "Tax Rates 4"},
    {"id": "5", "name": "Tax Rates 5"},
]

history = [
    {
        "user": "Anton De Meester",
        "created": "2024/01/01T05:00",
        "text": "Invoice uploaded by Anton De Meester",
        "type": "Added",
    },
    {
        "user": "Katarina Kostic De Meester",
        "created": "2023/01/01T05:00",
        "text": "Invoice Approved by Katarina Kostic with message: last time Anton",
        "type": "Approved",
    },
    {
        "user": "Benedikt Cucumber",
        "created": "2024/02/01T05:00",
        "text": None,
        "type": "Submitted",
    },
    {
        "user": "Yokoy Bot",
        "created": "2022/01/01T05:00",
        "text": "Invoice received from money@land.com",
        "type": "Received",
    },
    {
        "user": "Yokoy Bot",
        "created": "2021/01/01T05:00",
        "text": None,
        "type": "Lonely",
    },
]


invoices = [
    {
        "id": "0",
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 100,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 1",
        "issueDate": "2023-01-01",
        "dueDate": "2024-01-01",
        "submitter": ["Anton De Meester"],
        "approver": ["Katarina Kostic"],
        "status": "inApproval",
        "entity": "1",
    },
    {
        "id": "1",
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 77.5,
        "currency": "EUR",
        "invoiceNumber": "INVOICE 2",
        "issueDate": "2023-01-02",
        "dueDate": "2023-05-01",
        "submitter": ["Arnold Schumacher"],
        "approver": None,
        "status": "draft",
        "entity": "1",
    },
    {
        "id": "2",
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 4",
        "supplierId": "1235",
        "totalClaim": 99,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 3",
        "issueDate": "2023-01-31",
        "dueDate": "2023-03-01",
        "submitter": ["Benedikt Cucumber"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "1",
    },
    {
        "id": "3",
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 901,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 100",
        "issueDate": "2024-02-29",
        "dueDate": "2025-05-01",
        "submitter": ["Robert Not of Hear-o"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "1",
    },
    {
        "id": "4",
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 3",
        "supplierId": "1239",
        "totalClaim": 400,
        "currency": "EUR",
        "invoiceNumber": "INVOICE -1",
        "issueDate": "1993-09-02",
        "dueDate": "1995-03-01",
        "submitter": ["That guy from Hamilton"],
        "approver": ["Mike The Sub-boss"],
        "status": "exported",
        "entity": "1",
    },
    {
        "id": "5",
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 401.123,
        "currency": "CHF",
        "invoiceNumber": "SOMETHING",
        "issueDate": "1992-07-06",
        "dueDate": "1993-03-01",
        "submitter": ["Tomis Cruising"],
        "approver": None,
        "status": "readyForExport",
        "entity": "1",
    },
    {
        "id": "6",
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 0",
        "supplierId": "000",
        "totalClaim": 231,
        "currency": "CHF",
        "invoiceNumber": "Hello",
        "issueDate": "2000-01-01",
        "dueDate": "2001-03-01",
        "submitter": ["Ikea Matata"],
        "approver": None,
        "status": "new",
        "entity": "1",
    },
    {
        "id": "7",
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 11",
        "supplierId": "fjewifw",
        "totalClaim": 99,
        "currency": "USD",
        "invoiceNumber": "woops",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Yokoy Bot"],
        "approver": ["Phil the Real Boss"],
        "status": "new",
        "entity": "1",
    },
    {
        "id": "8",
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 100,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 1",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Anton De Meester"],
        "approver": ["Katarina Kostic"],
        "status": "inApproval",
        "entity": "1",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 77.5,
        "currency": "EUR",
        "invoiceNumber": "INVOICE 2",
        "issueDate": "2023-01-02",
        "dueDate": "2023-05-01",
        "submitter": ["Arnold Schumacher"],
        "approver": None,
        "status": "draft",
        "entity": "2",
        "id": "9",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 4",
        "supplierId": "1235",
        "totalClaim": 99,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 3",
        "issueDate": "2023-01-31",
        "dueDate": "2023-03-01",
        "submitter": ["Benedikt Cucumber"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "2",
        "id": "10",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 901,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 100",
        "issueDate": "2024-02-29",
        "dueDate": "2025-05-01",
        "submitter": ["Robert Not of Hear-o"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "2",
        "id": "11",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 3",
        "supplierId": "1239",
        "totalClaim": 400,
        "currency": "EUR",
        "invoiceNumber": "INVOICE -1",
        "issueDate": "1993-09-02",
        "dueDate": "1995-03-01",
        "submitter": ["That guy from Hamilton"],
        "approver": ["Mike The Sub-boss"],
        "status": "exported",
        "entity": "2",
        "id": "12",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 401.123,
        "currency": "CHF",
        "invoiceNumber": "SOMETHING",
        "issueDate": "1992-07-06",
        "dueDate": "1993-03-01",
        "submitter": ["Tomis Cruising"],
        "approver": None,
        "status": "readyForExport",
        "entity": "2",
        "id": "13",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 0",
        "supplierId": "000",
        "totalClaim": 231,
        "currency": "CHF",
        "invoiceNumber": "Hello",
        "issueDate": "2000-01-01",
        "dueDate": "2001-03-01",
        "submitter": ["Ikea Matata"],
        "approver": None,
        "status": "new",
        "entity": "2",
        "id": "14",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 11",
        "supplierId": "fjewifw",
        "totalClaim": 99,
        "currency": "USD",
        "invoiceNumber": "woops",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Yokoy Bot"],
        "approver": ["Phil the Real Boss"],
        "status": "new",
        "entity": "2",
        "id": "15",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 100,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 1",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Anton De Meester"],
        "approver": ["Katarina Kostic"],
        "status": "inApproval",
        "entity": "2",
        "id": "16",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 77.5,
        "currency": "EUR",
        "invoiceNumber": "INVOICE 2",
        "issueDate": "2023-01-02",
        "dueDate": "2023-05-01",
        "submitter": ["Arnold Schumacher"],
        "approver": None,
        "entity": "2",
        "status": "draft",
        "id": "17",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 4",
        "supplierId": "1235",
        "totalClaim": 99,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 3",
        "issueDate": "2023-01-31",
        "dueDate": "2023-03-01",
        "submitter": ["Benedikt Cucumber"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "3",
        "id": "18",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 901,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 100",
        "issueDate": "2024-02-29",
        "dueDate": "2025-05-01",
        "submitter": ["Robert Not of Hear-o"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "3",
        "id": "19",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 3",
        "supplierId": "1239",
        "totalClaim": 400,
        "currency": "EUR",
        "invoiceNumber": "INVOICE -1",
        "issueDate": "1993-09-02",
        "dueDate": "1995-03-01",
        "submitter": ["That guy from Hamilton"],
        "approver": ["Mike The Sub-boss"],
        "status": "exported",
        "entity": "3",
        "id": "20",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 401.123,
        "currency": "CHF",
        "invoiceNumber": "SOMETHING",
        "issueDate": "1992-07-06",
        "dueDate": "1993-03-01",
        "submitter": ["Tomis Cruising"],
        "approver": None,
        "status": "readyForExport",
        "entity": "3",
        "id": "21",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 0",
        "supplierId": "000",
        "totalClaim": 231,
        "currency": "CHF",
        "invoiceNumber": "Hello",
        "issueDate": "2000-01-01",
        "dueDate": "2001-03-01",
        "submitter": ["Ikea Matata"],
        "approver": None,
        "status": "new",
        "entity": "3",
        "id": "22",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 11",
        "supplierId": "fjewifw",
        "totalClaim": 99,
        "currency": "USD",
        "invoiceNumber": "woops",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Yokoy Bot"],
        "approver": ["Phil the Real Boss"],
        "status": "new",
        "entity": "3",
        "id": "23",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 100,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 1",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Anton De Meester"],
        "approver": ["Katarina Kostic"],
        "status": "inApproval",
        "entity": "3",
        "id": "24",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 77.5,
        "currency": "EUR",
        "invoiceNumber": "INVOICE 2",
        "issueDate": "2023-01-02",
        "dueDate": "2023-05-01",
        "submitter": ["Arnold Schumacher"],
        "approver": None,
        "status": "draft",
        "entity": "3",
        "id": "25",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 4",
        "supplierId": "1235",
        "totalClaim": 99,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 3",
        "issueDate": "2023-01-31",
        "dueDate": "2023-03-01",
        "submitter": ["Benedikt Cucumber"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "3",
        "id": "26",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 2",
        "supplierId": "1232",
        "totalClaim": 901,
        "currency": "CHF",
        "invoiceNumber": "INVOICE 100",
        "issueDate": "2024-02-29",
        "dueDate": "2025-05-01",
        "submitter": ["Robert Not of Hear-o"],
        "approver": ["Devis The Boss"],
        "status": "inReview",
        "entity": "4",
        "id": "27",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 3",
        "supplierId": "1239",
        "totalClaim": 400,
        "currency": "EUR",
        "invoiceNumber": "INVOICE -1",
        "issueDate": "1993-09-02",
        "dueDate": "1995-03-01",
        "submitter": ["That guy from Hamilton"],
        "approver": ["Mike The Sub-boss"],
        "status": "exported",
        "entity": "4",
        "id": "28",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 1",
        "supplierId": "1234",
        "totalClaim": 401.123,
        "currency": "CHF",
        "invoiceNumber": "SOMETHING",
        "issueDate": "1992-07-06",
        "dueDate": "1993-03-01",
        "submitter": ["Tomis Cruising"],
        "approver": None,
        "status": "readyForExport",
        "entity": "4",
        "id": "29",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": False,
        "supplier": "Supplier 0",
        "supplierId": "000",
        "totalClaim": 231,
        "currency": "CHF",
        "invoiceNumber": "Hello",
        "issueDate": "2000-01-01",
        "dueDate": "2001-03-01",
        "submitter": ["Ikea Matata"],
        "approver": None,
        "status": "new",
        "entity": "4",
        "id": "30",
    },
    {
        "lineItems": line_items,
        "history": history,
        "warning": True,
        "supplier": "Supplier 11",
        "supplierId": "fjewifw",
        "totalClaim": 99,
        "currency": "USD",
        "invoiceNumber": "woops",
        "issueDate": "2023-01-01",
        "dueDate": "2023-03-01",
        "submitter": ["Yokoy Bot"],
        "approver": ["Phil the Real Boss"],
        "status": "new",
        "entity": "4",
        "id": "31",
    },
]
